// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteTec.Infra.Data.Context;

namespace TesteTec.Infra.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TesteTec.Domain.Entities.Dimensao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomeDimensao")
                        .IsRequired()
                        .HasColumnName("NomeDimensao")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Dimensao");
                });

            modelBuilder.Entity("TesteTec.Domain.Entities.Morty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Morty");
                });

            modelBuilder.Entity("TesteTec.Domain.Entities.Rick", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdDimensao")
                        .HasColumnName("IdDimensao")
                        .HasColumnType("int");

                    b.Property<int>("IdMorty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdDimensao");

                    b.HasIndex("IdMorty");

                    b.ToTable("Ricks");
                });

            modelBuilder.Entity("TesteTec.Domain.Entities.Rick", b =>
                {
                    b.HasOne("TesteTec.Domain.Entities.Dimensao", "Dimensao")
                        .WithMany()
                        .HasForeignKey("IdDimensao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesteTec.Domain.Entities.Morty", "Morty")
                        .WithMany()
                        .HasForeignKey("IdMorty")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
